FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /build
COPY auth-service/ .
RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jdk
COPY --from=build /build/target/*.jar app.jar
EXPOSE 8081
ENTRYPOINT ["java","-jar","/app.jar"]