# ======================================================
# APPLICATION
# ======================================================

spring.application.name=API-GATEWAY

server.port=9090


# ======================================================
# EUREKA CONFIG
# ======================================================

eureka.instance.hostname=localhost

eureka.instance.prefer-ip-address=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

eureka.client.register-with-eureka=true

eureka.client.fetch-registry=true


# ======================================================
# GATEWAY DISCOVERY
# ======================================================

spring.cloud.gateway.discovery.locator.enabled=true

spring.cloud.gateway.discovery.locator.lower-case-service-id=true


# ======================================================
# AUTH SERVICE
# ======================================================

spring.cloud.gateway.routes[0].id=auth-service

spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE

spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**


# ======================================================
# USER SERVICE
# ======================================================

spring.cloud.gateway.routes[1].id=user-service

spring.cloud.gateway.routes[1].uri=lb://USER-SERVICE

spring.cloud.gateway.routes[1].predicates[0]=Path=/users/**


# ======================================================
# DRIVER SERVICE
# ======================================================

spring.cloud.gateway.routes[2].id=driver-service

spring.cloud.gateway.routes[2].uri=lb://DRIVER-SERVICE

spring.cloud.gateway.routes[2].predicates[0]=Path=/drivers/**


# ======================================================
# RIDE SERVICE
# ======================================================

spring.cloud.gateway.routes[3].id=ride-service

spring.cloud.gateway.routes[3].uri=lb://RIDE-SERVICE

spring.cloud.gateway.routes[3].predicates[0]=Path=/rides/**


# ======================================================
# PAYMENT SERVICE
# ======================================================

spring.cloud.gateway.routes[4].id=payment-service

spring.cloud.gateway.routes[4].uri=lb://PAYMENT-SERVICE

spring.cloud.gateway.routes[4].predicates[0]=Path=/payments/**


# ======================================================
# NOTIFICATION SERVICE
# ======================================================

spring.cloud.gateway.routes[5].id=notification-service

spring.cloud.gateway.routes[5].uri=lb://NOTIFICATION-SERVICE

spring.cloud.gateway.routes[5].predicates[0]=Path=/notifications/**


# ======================================================
# OTP SERVICE
# ======================================================

spring.cloud.gateway.routes[6].id=otp-service

spring.cloud.gateway.routes[6].uri=lb://NOTIFICATION-SERVICE

spring.cloud.gateway.routes[6].predicates[0]=Path=/otp/**


# ======================================================
# JWT SECRET
# ======================================================

jwt.secret=mySecretKeymySecretKeymySecretKey123456


# ======================================================
# LOGGING
# ======================================================

logging.level.org.springframework.cloud.gateway=DEBUG

logging.level.reactor.netty.http.client=DEBUG
# =========================================
# REDIS CONFIG
# =========================================

spring.data.redis.host=localhost

spring.data.redis.port=6379