server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/rapido_db?options=-c%20TimeZone=UTC
spring.datasource.username=rapido_user
spring.datasource.password=rapido_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true