server.port=8083

spring.application.name=DRIVER-SERVICE

# DATABASE

spring.datasource.url=jdbc:postgresql://localhost:5432/rapido_db
spring.datasource.username=rapido_user
spring.datasource.password=rapido_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# EUREKA

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# ACTUATOR

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# JWT

jwt.secret=mysecretkeymysecretkeymysecretkey123456
jwt.expiration=86400000

# REDIS CONFIG

spring.data.redis.host=localhost
spring.data.redis.port=6379