server.port=8084

spring.application.name=RIDE-SERVICE

spring.datasource.url=jdbc:postgresql://postgres:5432/rapido_db
spring.datasource.username=${DB_USERNAME:rapido_user}
spring.datasource.password=${DB_PASSWORD:rapido_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true

otel.service.name=ride-service
otel.traces.exporter=otlp
otel.metrics.exporter=none
otel.logs.exporter=none
otel.exporter.otlp.endpoint=http://jaeger.observability.svc.cluster.local:4317
otel.exporter.otlp.protocol=grpc
otel.traces.sampler=parentbased_traceidratio
otel.traces.sampler.arg=1.0

logging.pattern.level=%5p [traceId=%X{trace_id:-}, spanId=%X{span_id:-}]