spring.datasource.url=jdbc:postgresql://postgres:5432/rapido_db
spring.datasource.username=${DB_USERNAME:rapido_user}
spring.datasource.password=${DB_PASSWORD:rapido_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.application.name=RIDE-SERVICE
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true